data:
  raw_csv_train: './data/fake_users.csv'
  raw_csv_test: './data/fake_users_test.csv'
  processed_excel_train: './data/fake_users_train_processed.xlsx'
  processed_excel_test: './data/fake_users_test_processed.xlsx'
  inference_result_excel: './data/fake_users_test_processed_with_prediction.xlsx'
  target: Fake
  group_by: UserId
  event: Event
  features:
    percentage_of_event: [click_ad, send_email]
    count_of_columns: [Event]
    nunique_of_columns: [Category]
    top_count_percentage: [Category]
ml:
  model_path: './models'
  normalize: true
  pycaret_optimize: F1
  column_to_drop_for_training: [UserId, Event, Category]
  model_name: best_from_automl
